CREATE TABLE APLICACION (ID BIGINT NOT NULL, DESCRIPCION VARCHAR(255), JSONID BIGINT, NOMBRE VARCHAR(255), SINGLELOGIN BOOLEAN, D_ID BIGINT, PRIMARY KEY (ID))
CREATE TABLE CANAL (ID BIGINT NOT NULL, CODIGO VARCHAR(255), PROPIETARIO BOOLEAN, APP_ID BIGINT, PRIMARY KEY (ID))
CREATE TABLE DESARROLLADOR (ID BIGINT NOT NULL, APELLIDO VARCHAR(255), NICK VARCHAR(255), NOMBRE VARCHAR(255), PASS VARCHAR(255), PRIMARY KEY (ID))
CREATE TABLE PEDIDOJSON (ID BIGINT NOT NULL, JSONID INTEGER, METHOD VARCHAR(255), TIME TIMESTAMP, URL VARCHAR(255), PRIMARY KEY (ID))
CREATE TABLE PEDIDOMSJ (ID BIGINT NOT NULL, TIME TIMESTAMP, CANAL_ID BIGINT, PRIMARY KEY (ID))
CREATE TABLE PEDIDOPUSH (ID BIGINT NOT NULL, METHOD VARCHAR(255), TIME TIMESTAMP, URL VARCHAR(255), PRIMARY KEY (ID))
CREATE TABLE PEDIDOUSER (ID BIGINT NOT NULL, METHOD VARCHAR(255), TIME TIMESTAMP, URL VARCHAR(255), USUARIO_ID BIGINT, PRIMARY KEY (ID))
CREATE TABLE PERMISO (ID BIGINT NOT NULL, NOMBRE VARCHAR(255), PRIMARY KEY (ID))
CREATE TABLE REGISTRO (ID BIGINT NOT NULL, REGISTRER VARCHAR(255), PRIMARY KEY (ID))
CREATE TABLE ROL (ID BIGINT NOT NULL, NOMBRE VARCHAR(255), APLICACION_ID BIGINT, PRIMARY KEY (ID))
CREATE TABLE USUARIO (ID BIGINT NOT NULL, APELLIDO VARCHAR(255), NICK VARCHAR(255), NOMBRE VARCHAR(255), PASS VARCHAR(255), APLICACION_ID BIGINT, CANAL_ID BIGINT, PRIMARY KEY (ID))
CREATE TABLE APLICACION_PEDIDOJSON (Aplicacion_ID BIGINT NOT NULL, pedidosJson_ID BIGINT NOT NULL, PRIMARY KEY (Aplicacion_ID, pedidosJson_ID))
CREATE TABLE APLICACION_PEDIDOMSJ (Aplicacion_ID BIGINT NOT NULL, pedidosMsj_ID BIGINT NOT NULL, PRIMARY KEY (Aplicacion_ID, pedidosMsj_ID))
CREATE TABLE APLICACION_PEDIDOPUSH (Aplicacion_ID BIGINT NOT NULL, pedidosPush_ID BIGINT NOT NULL, PRIMARY KEY (Aplicacion_ID, pedidosPush_ID))
CREATE TABLE APLICACION_PEDIDOUSER (Aplicacion_ID BIGINT NOT NULL, pedidosUM_ID BIGINT NOT NULL, PRIMARY KEY (Aplicacion_ID, pedidosUM_ID))
CREATE TABLE APLICACION_PERMISO (Aplicacion_ID BIGINT NOT NULL, permisos_ID BIGINT NOT NULL, PRIMARY KEY (Aplicacion_ID, permisos_ID))
CREATE TABLE CANAL_PEDIDOMSJ (Canal_ID BIGINT NOT NULL, pedidosMsj_ID BIGINT NOT NULL, PRIMARY KEY (Canal_ID, pedidosMsj_ID))
CREATE TABLE REGISTRO_CANAL (canales_ID BIGINT NOT NULL, registrados_ID BIGINT NOT NULL, PRIMARY KEY (canales_ID, registrados_ID))
CREATE TABLE ROL_PERMISO (Rol_ID BIGINT NOT NULL, perms_ID BIGINT NOT NULL, PRIMARY KEY (Rol_ID, perms_ID))
CREATE TABLE USUARIO_ROL (Usuario_ID BIGINT NOT NULL, roles_ID BIGINT NOT NULL, PRIMARY KEY (Usuario_ID, roles_ID))
ALTER TABLE APLICACION ADD CONSTRAINT FK_APLICACION_D_ID FOREIGN KEY (D_ID) REFERENCES DESARROLLADOR (ID)
ALTER TABLE CANAL ADD CONSTRAINT FK_CANAL_APP_ID FOREIGN KEY (APP_ID) REFERENCES APLICACION (ID)
ALTER TABLE PEDIDOMSJ ADD CONSTRAINT FK_PEDIDOMSJ_CANAL_ID FOREIGN KEY (CANAL_ID) REFERENCES CANAL (ID)
ALTER TABLE PEDIDOUSER ADD CONSTRAINT FK_PEDIDOUSER_USUARIO_ID FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO (ID)
ALTER TABLE ROL ADD CONSTRAINT FK_ROL_APLICACION_ID FOREIGN KEY (APLICACION_ID) REFERENCES APLICACION (ID)
ALTER TABLE USUARIO ADD CONSTRAINT FK_USUARIO_CANAL_ID FOREIGN KEY (CANAL_ID) REFERENCES CANAL (ID)
ALTER TABLE USUARIO ADD CONSTRAINT FK_USUARIO_APLICACION_ID FOREIGN KEY (APLICACION_ID) REFERENCES APLICACION (ID)
ALTER TABLE APLICACION_PEDIDOJSON ADD CONSTRAINT FK_APLICACION_PEDIDOJSON_Aplicacion_ID FOREIGN KEY (Aplicacion_ID) REFERENCES APLICACION (ID)
ALTER TABLE APLICACION_PEDIDOJSON ADD CONSTRAINT FK_APLICACION_PEDIDOJSON_pedidosJson_ID FOREIGN KEY (pedidosJson_ID) REFERENCES PEDIDOJSON (ID)
ALTER TABLE APLICACION_PEDIDOMSJ ADD CONSTRAINT FK_APLICACION_PEDIDOMSJ_pedidosMsj_ID FOREIGN KEY (pedidosMsj_ID) REFERENCES PEDIDOMSJ (ID)
ALTER TABLE APLICACION_PEDIDOMSJ ADD CONSTRAINT FK_APLICACION_PEDIDOMSJ_Aplicacion_ID FOREIGN KEY (Aplicacion_ID) REFERENCES APLICACION (ID)
ALTER TABLE APLICACION_PEDIDOPUSH ADD CONSTRAINT FK_APLICACION_PEDIDOPUSH_Aplicacion_ID FOREIGN KEY (Aplicacion_ID) REFERENCES APLICACION (ID)
ALTER TABLE APLICACION_PEDIDOPUSH ADD CONSTRAINT FK_APLICACION_PEDIDOPUSH_pedidosPush_ID FOREIGN KEY (pedidosPush_ID) REFERENCES PEDIDOPUSH (ID)
ALTER TABLE APLICACION_PEDIDOUSER ADD CONSTRAINT FK_APLICACION_PEDIDOUSER_Aplicacion_ID FOREIGN KEY (Aplicacion_ID) REFERENCES APLICACION (ID)
ALTER TABLE APLICACION_PEDIDOUSER ADD CONSTRAINT FK_APLICACION_PEDIDOUSER_pedidosUM_ID FOREIGN KEY (pedidosUM_ID) REFERENCES PEDIDOUSER (ID)
ALTER TABLE APLICACION_PERMISO ADD CONSTRAINT FK_APLICACION_PERMISO_Aplicacion_ID FOREIGN KEY (Aplicacion_ID) REFERENCES APLICACION (ID)
ALTER TABLE APLICACION_PERMISO ADD CONSTRAINT FK_APLICACION_PERMISO_permisos_ID FOREIGN KEY (permisos_ID) REFERENCES PERMISO (ID)
ALTER TABLE CANAL_PEDIDOMSJ ADD CONSTRAINT FK_CANAL_PEDIDOMSJ_pedidosMsj_ID FOREIGN KEY (pedidosMsj_ID) REFERENCES PEDIDOMSJ (ID)
ALTER TABLE CANAL_PEDIDOMSJ ADD CONSTRAINT FK_CANAL_PEDIDOMSJ_Canal_ID FOREIGN KEY (Canal_ID) REFERENCES CANAL (ID)
ALTER TABLE REGISTRO_CANAL ADD CONSTRAINT FK_REGISTRO_CANAL_registrados_ID FOREIGN KEY (registrados_ID) REFERENCES REGISTRO (ID)
ALTER TABLE REGISTRO_CANAL ADD CONSTRAINT FK_REGISTRO_CANAL_canales_ID FOREIGN KEY (canales_ID) REFERENCES CANAL (ID)
ALTER TABLE ROL_PERMISO ADD CONSTRAINT FK_ROL_PERMISO_Rol_ID FOREIGN KEY (Rol_ID) REFERENCES ROL (ID)
ALTER TABLE ROL_PERMISO ADD CONSTRAINT FK_ROL_PERMISO_perms_ID FOREIGN KEY (perms_ID) REFERENCES PERMISO (ID)
ALTER TABLE USUARIO_ROL ADD CONSTRAINT FK_USUARIO_ROL_roles_ID FOREIGN KEY (roles_ID) REFERENCES ROL (ID)
ALTER TABLE USUARIO_ROL ADD CONSTRAINT FK_USUARIO_ROL_Usuario_ID FOREIGN KEY (Usuario_ID) REFERENCES USUARIO (ID)
CREATE SEQUENCE registro_id_seq START WITH 1
CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT DECIMAL(38), PRIMARY KEY (SEQ_NAME))
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('SEQ_GEN', 0)
CREATE SEQUENCE perm_id_seq START WITH 1
CREATE SEQUENCE des_id_seq START WITH 1
CREATE SEQUENCE app_id_seq START WITH 1
CREATE SEQUENCE canal_id_seq START WITH 1
CREATE SEQUENCE rol_id_seq START WITH 1
CREATE SEQUENCE pedidojson_id_seq START WITH 1
CREATE SEQUENCE pedidopush_id_seq START WITH 1
CREATE SEQUENCE pedidouser_id_seq START WITH 1
CREATE SEQUENCE user_id_seq START WITH 1
CREATE SEQUENCE pedidomsj_id_seq START WITH 1
