ALTER TABLE APLICACION DROP CONSTRAINT FK_APLICACION_id_persona
ALTER TABLE APLICACION DROP CONSTRAINT FK_APLICACION_id_aplicacion
DROP TABLE USUARIO CASCADE
DROP TABLE DESARROLLADOR CASCADE
DROP TABLE APLICACION CASCADE
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN'
